name: stripedart
description: Dart library for the Stripe API. https://stripe.com
version: 0.0.1
author: Luca Iaconelli
homepage: https://github.com/LucaIaconelli/stripe-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  json_annotation: ^3.0.0

dev_dependencies:
  test: ^1.14.3
  json_serializable: ^3.3.0
  build_runner: ^1.0.0